# Generated by Django 5.0.6 on 2024-06-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(max_length=254),
        ),
    ]
